version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: senhafraca
      
  api:
    build: ./source/api
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./source/api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./source/frontend
    command: ["npm", "start"]
    volumes:
      - ./source/frontend:/app/frontend
    ports:
      - "3000:3000"